config/routes.rb
Budgety::Application.routes.draw do

  match '/login' => "user#login", :as => :login
  match '/logout' => "user#logout", :as => :logout

  match '/home' => "index#home", :as => :home

  match '/t/new' => "transaction#new", :as => :new_transaction
  match '/t/edit' => "transaction#edit", :as => :edit_transaction
  match '/t/show' => "transaction#show", :as => :show_transaction
  match '/t/delete' => "transaction#delete", :as => :delete_transaction
  match '/t/show_month' => "transaction#show_month", :as => :show_month_transaction

  match '/b/new' => "budget_history#new", :as => :new_budget
  match '/b/update' => "budget_history#update", :as => :update_budget
  
  

  root :to => 'index#index'
end

app/views/index/home.html.haml
.h1{:style => "font-size:100px; text-align:center;"}
    - if @over_budget
        .div{:style => "color:red"}
            = "$" + number_with_precision(@current_budget, precision: 2)
    - else
        = "$" + number_with_precision(@current_budget, precision: 2)
%br
%br
.text-left.col-md-6
    = button_to "new transaction", "/t/new", :class => "btn btn-sm btn-success", :method => :get
.text-right.col-md-6
    = link_to "show all", "/t/show"
%br
%br
- if @current_month_transactions
    %table.table.table-striped.table-hover
        %thead
            %tr 
                %th Name
                %th Description
                %th Amount
                %th Date
                %th{:style => "width: 50px"}
                %th{:style => "width: 50px"}
        %tbody
            - @current_month_transactions.each do |c|
                %tr
                    %td #{c.name}
                    %td #{c.description}
                    %td $ #{number_with_precision(c.amount, precision: 2)}
                    %td #{c.date.to_formatted_s(:long)}
                    %td
                        = button_to "edit", edit_transaction_path({:transaction => c}), :class => "btn btn-primary"
                    %td 
                        = button_to "delete", delete_transaction_path({:transaction => c}), :class => "btn btn-danger", :confirm => "This transaction will be deleted."
- else
    %br
    %br
    .h4{:style => "font-weight:bold; text-align:center;"}
        = "Add a transaction"

app/views/index/index.html.haml
.h1{:style => "font-size:82px; text-align:center;"}
    = "Budgety"

.login-pos
    .well.login
        = form_tag({:controller => "user", :action => "login"},:method => "post") do
            = label "name", "Name:"
            = text_field_tag "name", ""
            %br
            = label "password", "Password:"
            = password_field_tag "password", ""
            %br
            %button.btn.btn-primary{:type => "submit", :style => "margin-top:15px;"} Login